-- Documents: user-owned files visible from the "My Documents" screen.
-- Apply via: paste into the Supabase SQL Editor (Dashboard → SQL Editor → Run).
--
-- Two flavours:
--   * source='uploaded'  → file uploaded by the user, linked to a property.
--   * source='generated' → snapshot generated by the app (e.g. a lease
--                          contract), linked to a lease.
-- The path always points to an object in the private 'documents' bucket.

create table public.documents (
  id          uuid        primary key default gen_random_uuid(),
  owner_id    uuid        not null references auth.users on delete cascade,
  property_id uuid        references public.properties on delete cascade,
  lease_id    uuid        references public.leases on delete cascade,
  name        text        not null,
  path        text        not null,
  mime_type   text        not null,
  size        bigint      not null,
  source      text        not null check (source in ('uploaded', 'generated')),
  created_at  timestamptz not null default now()
);

create index documents_owner_id_idx    on public.documents(owner_id);
create index documents_property_id_idx on public.documents(property_id);
create index documents_lease_id_idx    on public.documents(lease_id);

alter table public.documents enable row level security;

create policy "Owners select own documents"
  on public.documents for select
  using (owner_id = auth.uid());

create policy "Owners insert own documents"
  on public.documents for insert
  with check (owner_id = auth.uid());

create policy "Owners delete own documents"
  on public.documents for delete
  using (owner_id = auth.uid());

create policy "Admins read all documents"
  on public.documents for select
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- Private bucket; reads/writes go through the service role from server
-- actions, mirroring the property-photos / tenant-documents pattern.
insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;